name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/github-ec2-key
          chmod 600 ~/.ssh/github-ec2-key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/github-ec2-key ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_PATH }} 
            git pull origin master
            npm install --production
            pm2 restart all || pm2 start app.js   # adjust command if needed
          EOF
