name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github-ec2-key
          chmod 600 ~/.ssh/github-ec2-key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/github-ec2-key ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set e
            cd ${{ secrets.EC2_PATH }} 
            git pull origin master
            npm install --production
            echo "Building the project..."
            npm run build || echo "No build step"
            pm2 restart all || pm2 start app.js   # adjust command if needed
            pm2 save
          EOF
